on:
  release:
    types: created

name: Publish to Test PyPI

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: Use Python Dependency Cache
        uses: actions/cache@v1.0.3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
          restore-keys: ${{ runner.os }}-poetry-

      - name: Install Dependencies
        run: |
          source $HOME/.poetry/env
          poetry install --no-dev

      - name: Build & Publish
        run: |
          source $HOME/.poetry/env
          poetry config repositories.testpypi https://test.pypi.org/legacy
          poetry build 
          poetry publish -u __token__ -p ${{ secrets.TEST_PYPI_TOKEN }} -r testpypi
