name: CD

on:
  release:
    types: [published]

jobs:
  deploy:
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Python Setup
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install Poetry
        run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

      - name: Install Dependencies
        run: |
          source $HOME/.poetry/env
          poetry install --no-dev

      - name: Build
        run: |
          source $HOME/.poetry/env
          poetry build

      - name: Publish to PyPI
        run: |
          source $HOME/.poetry/env
          poetry publish -u __token__ -p ${{ secrets.PYPI_TOKEN }}
